---
name: 👷 Continuous Integration

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      HUGO_VERSION:
        default: latest
        required: false
        type: string
    secrets:
      TF_API_TOKEN:
        required: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  scan:
    if: ${{ !endsWith(github.repository, '-template') }}
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: bridgecrewio/checkov-action@v12
        with:
          config_file: .checkov.yml
          output_format: cli
          output_file_path: console

  build:
    if: ${{ !endsWith(github.repository, '-template') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: chetan/git-restore-mtime-action@v2

      - name: Install `hugo`
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ inputs.HUGO_VERSION }}
          extended: true
      - uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/hugo-cache/modules
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}

      - name: Build site
        run: PATH=.:$PATH make build

      - uses: actions/upload-artifact@v3
        with:
          name: public_html
          path: public/

  plan:
    if: ${{ !endsWith(github.repository, '-template') }}
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Cache terraform modules/providers
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/infra/.terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('infra/.terraform.lock.hcl') }}
      - name: Run `terraform init`
        run: terraform -chdir=infra init -input=false
      - name: Run `terraform plan`
        run: terraform -chdir=infra plan -input=false
