---
name: 👷 Continuous Integration

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      HUGO_VERSION:
        default: latest
        required: false
        type: string
    secrets:
      TF_API_TOKEN:
        required: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  build:
    if: ${{ !endsWith(github.repository, '-template') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: chetan/git-restore-mtime-action@v2

      - name: Install `hugo`
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ inputs.HUGO_VERSION }}
          extended: true
      - name: Cache hugo modules
        uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build site
        run: PATH=.:$PATH make build

      - uses: actions/upload-artifact@v3
        with:
          name: public_html
          path: public/

  plan:
    if: ${{ !endsWith(github.repository, '-template') }}
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Run `terraform init`
        run: terraform -chdir=infra init -input=false
      - name: Run `terraform plan`
        run: terraform -chdir=infra plan -input=false
