---
name: 👷 Lint

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.0
